apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: jekyll
  labels:
    app: jekyll
spec:
  type: NodePort
  ports:
    - name: jekyll
      port: 4000
      nodePort: 30001
  selector:
    app: jekyll
