apiVersion: v1
kind: ConfigMap
metadata:
  name: beian-conf
  namespace: blog
data:
  beian.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name www.linuxtian.top;
        
            error_page  403 /403.html;
            error_page  404 /404.html;
            error_page  500 502 503 504 /50.html;

            location = /403.html {
               root /etc/nginx/stylepage/html;
            }

            location = /404.html {
               root /etc/nginx/stylepage/html;
            }

            location = /50.html {
               root /etc/nginx/stylepage/html;
            }

        #return 200 "This is the default website.";
    
        location / {
          root /opt/;
          index beian.html;
        }
    }
