apiVersion: v1
kind: ConfigMap
metadata:
  name: jekyll-conf
  namespace: jekyll
data:
  jekyll.conf: |
    server {
            listen 443 ssl;
            server_name blog.linuxtian.top;

            ssl_certificate /etc/nginx/cert/tls.crt;
            ssl_certificate_key /etc/nginx/cert/tls.key;
            ssl_session_timeout 5m;
            ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
            ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
            ssl_prefer_server_ciphers on;
    

            error_page  403 /403.html;
            error_page  404 /404.html;
            error_page  500 502 503 504 /50.html;

            location = /403.html {
               root /etc/nginx/stylepage/html;
            }

            location = /404.html {
               root /etc/nginx/stylepage/html;
            }

            location = /50.html {
               root /etc/nginx/stylepage/html;
            }

            location / {
                   sendfile off;
                   proxy_pass         http://jekyll:4000;
                   proxy_redirect     default;
                   proxy_http_version 1.1;
                   proxy_set_header   Connection        $connection_upgrade;
                   proxy_set_header   Upgrade           $http_upgrade;
                   proxy_set_header   Host              $http_host;
                   proxy_set_header   X-Real-IP         $remote_addr;
                   proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
                   proxy_set_header   X-Forwarded-Proto $scheme;
                   proxy_max_temp_file_size 0;
                   client_max_body_size       10m;
                   client_body_buffer_size    128k;
                   proxy_connect_timeout      90;
                   proxy_send_timeout         90;
                   proxy_read_timeout         90;
                   proxy_buffering            off;
                   proxy_request_buffering    off;
                   proxy_set_header Connection "";
                   proxy_ignore_headers Set-Cookie Cache-Control;
                   proxy_next_upstream http_502 http_504 error timeout invalid_header;
    
                   # 禁止国外IP访问，返回报错403
                   if ($allowed_country = no) {
                   return 403;
                         }
    
                  # 防止爬虫抓取
                  if ($http_user_agent ~* "360Spider|JikeSpider|Spider|spider|bot|Bot|2345Explorer|curl|wget|webZIP|qihoobot|Baiduspider|Googlebot|Googlebot-Mobile|Googlebot-Image|Mediapartners-Google|Adsbot-Google|Feedfetcher-Google|Yahoo! Slurp|Yahoo! Slurp China|YoudaoBot|Sosospider|Sogou spider|Sogou web spider|MSNBot|ia_archiver|Tomato Bot|NSPlayer|bingbot"){
                  return 403;
                   }
    
                   }
    
                  # 文件服务
                  location /data {
                    autoindex on; # 索引
                    autoindex_exact_size off; # 显示文件大小
                    autoindex_localtime on; # 显示文件时间
                    root /; # 存放文件的目录
                    # 登录认证配置
                    auth_basic "secret";
                    auth_basic_user_file /data/1-jekyll博客相关/passwd.db;
                  }
    
                  # 解决 gitalkError: Network Error
    
                   add_header Access-Control-Allow-Origin '*.weiyigeek.top';
                   add_header Access-Control-Allow-Methods 'GET,POST,OPTIONS';
                   add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
    
    
                   # 插入 Gitalk Auth Use 关键点
                   location /github {
                     if ($request_method = 'OPTIONS') {
                     return 204;
                     }
                   proxy_pass https://github.com/; # 注意尾部斜杠不能少
    
                   }
    
    }
